# Generated by Django 3.2 on 2021-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_name_user_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workselect',
            name='name',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
